### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AeidaSB** [tastybento/multiworldmoney#11]
Hey im wondering if you can help? tastybento released a multiworldmoney plugin that i've downloaded and for /balance it displays MV aliases however for /pay when using the placeholder [world] it displays the long name rather than the alias I'm wanting but in the config i can't find an alternative

i contacted on discorded and got this reply,
PoslovitchToday at 14:04
It'd be better to file a feature request for that I think. I don't know if such commands already exist in that addon

hopefully you could help either allow the use of papi or an alternative way of renaming whats printed for the worlds

this is a great plugin you should update and create a paid version there isn't many alternatives

![image](https://user-images.githubusercontent.com/63429021/80492407-de21ae80-895b-11ea-810c-7efa300b7f6f.png)

**Comment by tastybento** [comment]
I haven't touched this code in a long time, but let's see what I can do.
Let me clarify: you would like it to say:

$10 has been sent to JDBase95 in Skyblock?

**Comment by AeidaSB** [comment]
Yes that would be brilliant if its possible. It's a lot more tasteful on the eyes, thank you tastybento

**Comment by tastybento** [comment]
Check out release 3.2 on the releases tab and let me know if that works for you.
