### ISSUE TITLE
Money lost when sent in a different world

### ISSUE THREAD

**Issue by AeidaSB** [tastybento/multiworldmoney#12]
Okay so the new update looks good with the name of the worlds, everything seems to be running fine in that aspect so good job

However I've encountered a new problem for example i have two worlds Spawn and Skyblock

If User A in in the spawn world and user B is in skyblock world and user B sends user A money then it disappears, for example,
 
![image](https://user-images.githubusercontent.com/63429021/80806142-c2174a80-8bb1-11ea-9c56-0db208946e9b.png)

It seems to be fine when both users are in the same world but if not the money is lost

![image](https://user-images.githubusercontent.com/63429021/80806229-03a7f580-8bb2-11ea-8192-5bf2099e72c3.png)

**Comment by AeidaSB** [comment]
I've been using per world inventory to save my players inventory maybe could be interfering? I'm going to try with Multiverse Inventory and i will update you on the result

**Comment by AeidaSB** [comment]
Please close this issue because everything is working perfectly with MultiWorldMoney and Multiverse-Inventories on paper 1.15.2! Thank you for the update Bento

**Comment by tastybento** [comment]
ok!
