### ISSUE TITLE
/pay not checking if sender has enough money

### ISSUE THREAD

**Issue by sorenjacobjensen** [tastybento/multiworldmoney#2]
private void pay(Player target, Player player, double amount) does not check if the sender actually has enough Money on their balance to send money if they are in the same world as the target or if the target is the sender itself. That way a player can boost his own money by sending large amounts of money to him/herself.

The check transactionSuccess() from the !SameWorld should be applied to pay() as well

**Comment by tastybento** [comment]
THANKS!

I've just posted an update to V2.1.

I put in the check to stop payments that cannot be made. Also, , there's no reason why players should be able to pay themselves, so I put in a check for that too.
